"""Initial migration

Revision ID: 055ae65f0027
Revises: 
Create Date: 2025-10-14 18:10:06.821339

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '055ae65f0027'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('sex',
               existing_type=mysql.CHAR(length=1),
               type_=sa.String(length=1),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('sex',
               existing_type=sa.String(length=1),
               type_=mysql.CHAR(length=1),
               existing_nullable=True)

    # ### end Alembic commands ###
